compress_assets: on
gzip_assets: off

javascripts:
  foundation:
    - js/jquery.reveal.js
    - js/jquery.orbit-1.4.0.js
    - js/jquery.customforms.js
    - js/jquery.placeholder.min.js
    - js/jquery.tooltips.js
